CREATE DATABASE crud;

USE crud;

CREATE TABLE employees (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    salary INT(10) NOT NULL
);

GRANT ALL PRIVILEGES ON crud.* TO 'root'@'localhost' IDENTIFIED BY 'abc123';
FLUSH PRIVILEGES;
